# Generated by Django 5.2.1 on 2025-06-02 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='submission_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
