# Generated by Django 5.2.1 on 2025-06-02 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_studentanswer_submission_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='submission_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
