# Generated by Django 5.2.1 on 2025-06-06 14:13

from django.db import migrations

# Generated by Django 5.2.1 on 2025-06-06 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_announcement_description'),
    ]

    operations = [
    ]
